theme: jekyll-theme-hacker
title: krishna kakade
author: krishnağŸ±â€ğŸ’»
email: krishnadevz@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning FullStack-Developer,Passion for ComputersğŸ±â€ğŸ’» 
  and Science,Protonï¸â„<MyWorldFoundedInğŸ±â€ğŸ’»ğŸ’»ğŸŒ„ğŸ’­/> 

# social links
twitter_username: krishndevz # DO NOT include the @ character, or else the build will fail!
github_username:  krishndevz # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
